name: Dev Workflow
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Generate .env from Secrets
        run: |
          echo "AMOCRM_ACCOUNTS=${{ secrets.DEV_AMOCRM_ACCOUNTS }}" >> .env
          echo "AMOCRM_BASEURL=${{ secrets.DEV_AMOCRM_BASEURL }}" >> .env
          echo "AMOCRM_CALLSTATS=${{ secrets.DEV_AMOCRM_CALLSTATS }}" >> .env
          echo "AMOCRM_URL=${{ secrets.DEV_AMOCRM_URL }}" >> .env
          echo "AMO_LOGIN=${{ secrets.DEV_AMO_LOGIN }}" >> .env
          echo "AMO_PASSWORD=${{ secrets.DEV_AMO_PASSWORD }}" >> .env
          echo "APP_ENV=${{ secrets.DEV_APP_ENV }}" >> .env
          echo "DB_HOST=${{ secrets.DEV_DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DEV_DB_NAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DEV_DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DEV_DB_USER }}" >> .env
          echo "TELEGRAM_API_TOKEN=${{ secrets.DEV_TELEGRAM_API_TOKEN }}" >> .env
      - name: Run Docker Compose
        run: docker compose -f docker-compose.dev.yml up -d --build